### ISSUE TITLE
Pretraining

### ISSUE THREAD

**Issue by konyul** [hollow-503/UniM2AE#3]
Hi, Thanks for sharing such a great work. Did you use swint-nuImages checkpoint for BEVFusion-SST or UniM2AE?

**Comment by hollow-503** [comment]
Sorry for the late reply. We used the swint-nuImages checkpoint for fair comparison with other SOTA methods. It should be clarified that we demonstrate the effectiveness of UniM2AE on camera encoder in our paper. We used it just for the alignment with other SOTA methods.

**Comment by konyul** [comment]
Thank you for the reply
